<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>elevator_interaction_flexbe_states</name>
  <version>0.0.0</version>
  <description>FlexBE states for elevator interaction system</description>
  <maintainer email="jerryzhang7@126.com">agilex03</maintainer>
  <license>Apache License 2.0</license>

  <depend>flexbe_core</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_srvs</depend>
  <depend>audio_common_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
    <flexbe_states />
  </export>
</package>
