locations:
  kitchen:
    x: -5.718
    y: -5.606
    theta: -1.306
    chinese_name: "厨房"
    arrival_message: "I've brought you to the kitchen. If I'm not mistaken, there should be various vegetables on the countertop. Please check if you can find what you need."
    chinese_arrival_message: "我已经带你走到厨房了，我没记错的话，厨房台面上会有许多蔬菜，你可以看看有没有你要的？"
  lab:
    x: 3.0
    y: 4.0
    theta: 1.57
    chinese_name: "实验室"
    arrival_message: "We've arrived at the lab. This is where research and experiments are conducted."
    chinese_arrival_message: "我们已经到达实验室了。这里是进行研究和实验的地方。"
  library:
    x: 5.0
    y: 6.0
    theta: 3.14
    chinese_name: "图书馆"
    arrival_message: "We've arrived at the library. Here you can find a variety of books and resources."
    chinese_arrival_message: "我们已经到达图书馆了。这里有各种各样的书籍和资源。"

